---
- apt: name=mysql-server state=present

- git: repo=https://github.com/kevinburke/crontroller.git
       dest=/root/crontroller
       version='1.0'
       accept_hostkey=yes

- file: path=/root/bin
        state=directory
        mode=0755

- file: path=/root/tmp
        state=directory
        mode=0755

- name: copy crontroller script to the bin directory
  command: cp /root/crontroller/crontroller /root/bin/crontroller

- name: copy backup script
  ansible.builtin.template:
    src: backup.sh
    dest: /root/bin/mysql-backup
    mode: 0700

- name: install cron to backup mysql database
  cron:
    name: "back up mysql database"
    hour: 22
    minute: 11
    job: "/root/bin/crontroller -e 'kev+crontroller@inburke.com' -f cron@inburke.com -a bash -c '/root/bin/mysql-backup' "

- name: create mysql run directory file
  file:
    path: /var/run/mysqld
    state: directory
    owner: mysql
    group: adm
    mode: "0755"

# having trouble with the "service" module on Docker
- name: Start mysql service, if not started
  ansible.builtin.command: service mysql start
