---
- name: Install stage.eastbayforeveryone.org
  hosts: all

  roles:
    - role: common
    - role: eastbayforeveryone.org
      tarsnap_enabled: false
      user: eb4e-stage
      directory: "/home/{{ user }}"
      wordpress_version: '5.8.3'
      akismet_version: '4.2.1'
      wordpress_ssl_enabled: true
      wordpress_debug: false
      domain: stage.eastbayforeveryone.org
      redirect_domains:
      - stage2.eastbayforeveryone.org
      - www.stage.eastbayforeveryone.org

# certbot certonly --non-interactive --webroot -w /home/eb4e-stage/public -d stage2.eastbayforeveryone.org --renew-by-default --email kevin@burke.dev --text --agree-tos
# certbot certonly --non-interactive --webroot -w /home/eb4e-stage/public -d stage.eastbayforeveryone.org --renew-by-default --email kevin@burke.dev --text --agree-tos
# certbot certonly --non-interactive --webroot -w /home/eb4e-stage/public -d www.stage.eastbayforeveryone.org --renew-by-default --email kevin@burke.dev --text --agree-tos
