---
- git: repo=https://github.com/kevinburke/crontroller.git
       dest=/home/letsencrypt/crontroller
       accept_hostkey=yes
       version='1.0'
  become: yes
  become_user: letsencrypt

- file: path=/home/letsencrypt/bin
        state=directory
        mode=0755
        group=letsencrypt
  become: yes
  become_user: letsencrypt

- name: copy crontroller script to the bin directory
  command: cp /home/letsencrypt/crontroller/crontroller /home/letsencrypt/bin/crontroller
  become: yes
  become_user: letsencrypt

- file: path=/home/letsencrypt/cfg
        state=directory
        mode=0755
        group=letsencrypt
  become: yes
  become_user: letsencrypt

- file: path=/home/letsencrypt/cfg/cron
        state=directory
        mode=0755
        group=letsencrypt
  become: yes
  become_user: letsencrypt

- template: src=cron.env
            dest=/home/letsencrypt/cfg/cron/env
            owner=letsencrypt
            group=letsencrypt
            mode=0400

- file: path=/home/letsencrypt/logs
        state=directory
        mode=0755
        group=letsencrypt
  become: yes
  become_user: letsencrypt

- apt: name=anacron state=present

- name: install cron to renew certificates
  cron: name="renew certificates"
        hour=0
        minute=32
        job="cd /home/letsencrypt; . /home/letsencrypt/cfg/cron/env; /home/letsencrypt/bin/crontroller -e 'kevin+crontroller@burke.dev' -f cron@burke.dev -a bash -c '. /home/letsencrypt/cfg/cron/env ; cd /opt/certbot && git checkout master && git pull origin master && /usr/bin/certbot renew --non-interactive --email kevin+eb4e@burke.dev --agree-tos ; /etc/init.d/nginx restart' "
