---

# https://github.com/pmbauer/ansible-tarsnap/blob/master/tasks/tarsnap.yml
# https://www.tarsnap.com/compiling.html

- name: Install dependencies for Tarsnap
  apt:
    pkg: [
      'gcc',
      'gnupg',
      'libc6-dev',
      'make',
      'libssl-dev',
      'zlib1g-dev',
      'e2fslibs-dev',
    ]

- name: Check if tarsnap {{ tarsnap_version }} is installed
  shell: tarsnap --version | grep {{ tarsnap_version }} --color=never
  register: tarsnap_installed
  changed_when: "tarsnap_installed.stderr != ''"
  ignore_errors: yes

- name: Download the current tarsnap code signing key
  when: tarsnap_installed is failed
  get_url:
    url=https://www.tarsnap.com/tarsnap-signing-key-2021.asc
    dest=/root/tarsnap-signing-key.asc

- name: Add the tarsnap code signing key to your list of keys
  when: tarsnap_installed is failed
  command:
    gpg --import tarsnap-signing-key.asc
    chdir=/root/

- name: Download tarsnap SHA file
  when: tarsnap_installed is failed
  get_url:
    url="https://www.tarsnap.com/download/tarsnap-sigs-{{ tarsnap_version }}.asc"
    dest="/root/tarsnap-sigs-{{ tarsnap_version }}.asc"

- name: get the SHA256sum for this tarsnap release
  when: tarsnap_installed is failed
  shell: >
    gpgResult=`gpg --decrypt tarsnap-sigs-{{ tarsnap_version }}.asc 2>/dev/null`;
    echo ${gpgResult#*=};
  args:
    executable: /bin/bash
    chdir: /root
  register: tarsnap_sha

- debug:
    var: tarsnap_sha

- name: Download Tarsnap source
  when: tarsnap_installed is failed
  get_url:
    url="https://www.tarsnap.com/download/tarsnap-autoconf-{{ tarsnap_version }}.tgz"
    dest="/root/tarsnap-autoconf-{{ tarsnap_version }}.tgz"
    checksum=sha256:{{ tarsnap_sha.stdout_lines[0] }}

- name: Decompress Tarsnap source
  when: tarsnap_installed is failed
  unarchive:
    src=/root/tarsnap-autoconf-{{ tarsnap_version }}.tgz
    copy=no
    dest=/root
    creates=/root/tarsnap-autoconf-{{ tarsnap_version }}/COPYING

- name: Configure Tarsnap for local build
  when: tarsnap_installed is failed
  command: ./configure chdir=/root/tarsnap-autoconf-{{ tarsnap_version }} creates=/root/tarsnap-autoconf-{{ tarsnap_version }}/Makefile

- name: Build and install Tarsnap
  when: tarsnap_installed is failed
  command: make all install clean chdir=/root/tarsnap-autoconf-{{ tarsnap_version }} creates=/usr/local/bin/tarsnap

- name: Create Tarsnap cache directory
  file: state=directory path=/root/cache/tarsnap

- name: Create keys directory
  file: state=directory path=/root/keys

- name: copy conf
  copy: src=tarsnaprc
        dest=/usr/local/etc/tarsnap.conf
        mode=0644

# TODO: you need to run tarsnap-keygen and enter your tarsnap password to get
# this to work.
