# The first time the box boots, _something_ needs to run apt-get update
- name: "Update Repository cache"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true

- name: Install base dependencies
  ansible.builtin.apt:
    name: [
      'apt-transport-https',
      'sudo',
      'python3-pip',
    ]
    state: latest

- name: Ensure pip is up to date
  command: pip install --upgrade pip virtualenv
